name: Upload package PackageCloud.io
description: Upload a package to PackageCloud.io
branding:
  icon: package
  color: blue
inputs:
  deb-package-name:
    description: Name of the deb package to upload
    required: false
  rpm-package-name:
    description: Name of the rpm package to upload
    required: false
  packagecloud-username:
    description: The username to use on PackageCloud.io
    required: true
  packagecloud-repo:
    description: The repository to upload on this user
    required: true
  packagecloud-token:
    description: The Token with push access
    required: true
runs:
  using: composite
  steps:
    - name: Upload package to PackageCloud.io
      run: ${{ github.action_path }}/push.sh
      shell: bash
      env:
        DEB_PACKAGE_NAME: ${{ inputs.deb-package-name }}
        RPM_PACKAGE_NAME: ${{ inputs.rpm-package-name }}
        PACKAGECLOUD_USERNAME: ${{ inputs.packagecloud-username }}
        PACKAGECLOUD_REPO: ${{ inputs.packagecloud-repo }}
        PACKAGECLOUD_TOKEN: ${{ inputs.packagecloud-token }}
